azure:
  store_build_artifacts: true
bot:
  automerge: true
  check_solvable: true
conda_build:
  error_overlinking: false
github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
